name: CI/CD Pipeline
on:
  push:
    branches:
      - main
    paths:
      - '.github/workflows/actions.yml'
      - 'index.html'
      - 'style.css'
      - 'script.js'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3