name: CI/CD do Portfólio (meuportfph.site)

on:
  push:
    branches:
      - main
    paths:
      - 'CNAME'
      - 'index.html'
      - 'style.css'
      - 'script.js'
      - 'images/**'
      - 'PaginaCLI/**'
      - 'PaginaWeb/**'
      - 'PaginaWeb/ambiente.yml'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: 1. Checkout do Repositório
        uses: actions/checkout@v4

      - name: 2. Criar arquivo .nojekyll
        # Garante que arquivos com '_' no nome (comum em assets) não sejam ignorados
        run: touch .nojekyll

      - name: 3. Upload do Artefato
        uses: actions/upload-pages-artifact@v3
        with:
          path: .

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    
    runs-on: ubuntu-latest
    needs: build
    
    permissions:
      pages: write 
      id-token: write 
      
    steps:
      - name: 4. Deploy no GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4